### PR TITLE
Added player and player movement.

### PR DESCRIPTION
**Pull request by mk10-13**
Added player and player movement.

### CODE REVIEW

**Review by EVanDyke — CHANGES_REQUESTED** [review]
The playerMovement.cs file seems to be lacking 2D mechanics. I believe that the Vector3 that is used on line 14 does not work well with a 2D game type. There also is not a way to add force to the player object such as a rigidBody2d. This may be an error that can led to issues with the player movement.
This video may be a good reference for what is needed for 2D player controls: 
https://unity3d.com/learn/tutorials/projects/2d-ufo-tutorial/controlling-player?playlist=25844

Please address these possible issues prior to merging. Thank you.

**Review by Mdaviet — CHANGES_REQUESTED** [review]
This feels like raw code that has been untested because there is no player asset which could be interacted with.  I believe that the Vector3 object on line 14 is meant for a 3d environment and should be made into a Vector2.

Please change Vector3 into a Vector2 and then create an asset to test the script operates as intended.

Additional note: do not upload files to github!  If you need help working with git, let me know and I'll help you make a successful push because uploading files tends to put them in the wrong place.

**Review by Mdaviet — CHANGES_REQUESTED** [review]
This appears to be the wrong version of your changes.  This looks like what we worked on in Unity 2017.1, and the scripts are incomplete.  The player does not interact at all with tiles, and the movement script was separated. 

Please check that you made appropriate changes in Unity 2017.3.1f1, and then push again.

**Comment by leiqian-nmsu** [comment]
Hi everyone,

I found Very good videos showing how to prepare everything step by step.

https://www.youtube.com/watch?v=I0IVZhHNarg&list=PLX-uZVK_0K_6VXcSajfFbXDXndb6AdBLO&index=2

Hope you can find they are helpful.

**Comment by EVanDyke** [comment]
Check these fixes to the player. @mk10-13 @Mdaviet @leiqian-nmsu

**Review by EVanDyke — APPROVED** [review]
Looks good. Thanks for catching that.

**Review by Mdaviet — APPROVED** [review]
Final version pushed by lei is working.  Looks good to me.

**Pull request merged**
