### PR TITLE
Tile collisions

### PR DESCRIPTION
**Pull request by EVanDyke**
Add collisions to the rocks and trees. At this point the log pickups will have solid player collisions as well, this will be addressed in a different branch.

### CODE REVIEW

**Review by Mdaviet — CHANGES_REQUESTED** [review]
-  Why did you need to revert a previous commit?  I see that you want to address an issue with the logs in a separate branch, but what specific need was there for the reverted commit?
-  There is a merge conflict with "Test Environment.unity" which must be resolved before we can push these changes.
-  "Test Environment.unity" can now only be opened as an empty scene with no assets, cameras, or any other elements.  This is likely a part of the merge conflict and must be resolved.

**Comment by EVanDyke** [comment]
The reason I reverted that commit is that it deals with the logs as tiles. I do not believe that this is the right way to make the pickups, they need to be sprites. I am planning to work on those in the player-pickups branch. 

I will look into the merge conflict. Something may have gone wrong with my files. Any suggestions you have for this would be appreciated.

**Comment by Mdaviet** [comment]
Regarding the revert, I think that it would have been more appropriate to make a new commit, or just leave it and create an issue.  By reverting it, you effectively destroyed any documentation of what you thought was more appropriate to go in a different branch.

I have no idea what exactly the issue is or how to solve it with the .unity scene.  I played around for 20 minutes or so without any fixes, so I'm not sure what to do at this point.

**Comment by EVanDyke** [comment]
Is there a way to undo this commit so that I can rework it?

**Comment by Mdaviet** [comment]
You may actually want to just start a new branch and make the changes again.  It sucks, but it may be easier to abandon the work than try to fix it.

**Pull request closed without merging**
