### PR TITLE
Runes

### PR DESCRIPTION
**Pull request by EVanDyke**
Added the scroll images to rune sprites and tagged sprites according to rune type.

### CODE REVIEW

**Review by Mdaviet — CHANGES_REQUESTED** [review]
The runes and the transmutation circle all do not have tags.  Please get the appropriate tags assigned so that the scripts have the appropriate handling.

**Comment by EVanDyke** [comment]
Found an issue with the placement of the box collider on the transmutation circle. Crafting is now working for all runes.

**Review by Mdaviet — APPROVED** [review]

**Comment by leiqian-nmsu** [comment]
Great Job!

**Review by leiqian-nmsu — APPROVED** [review]
Good job!

**Pull request merged**
